from datetime import datetime
from enum import Enum
from typing import Annotated, ClassVar, Literal

from pydantic import AfterValidator, BaseModel, Field
from schemas.message_content_type import MessageContentType
from schemas.message_role import MessageRole
from schemas.recipes import UserRecipe
from schemas.safety_guards import SafetyGuardResult


class UserMessagePayload(BaseModel):
    """Payload for a user message."""

    id: str = Field(description="The message's id")
    content: str = Field(description="The message's text content")

class BaseMessage(BaseModel):
    """A message in a thread."""

    id: str = Field(description="The message's id")
    user_id: str = Field(description="The associated user's id")
    thread_id: str = Field(description="The associated thread's id")
    role: MessageRole = Field(description="Who created the message")
    content_type: MessageContentType = Field(description="The message's content type")
    created_at: str = Field(description="The message's creation timestamp in ISO string format")
    updated_at: str = Field(description="The message's last update timestamp in ISO string format")

class BaseMessageParent(BaseModel):
    parent_id: str | None = Field(
        default=None, description="The parent message's id if it's a reply"
    )

class BaseMessageTextContent(BaseModel):
    text_content: str | None = Field(
        default=None, description="The message's text content if it's a text message"
    )

class BaseMessageRecipeGeneration(BaseModel):
    recipe_id: str | None = Field(
        default=None, description="The associated recipe's id if it's a recipe message"
    )
    is_recipe_generation_started: bool | None = Field(
        default=None, description="Whether the message is the start of a recipe generation"
    )
    is_recipe_generation_completed: bool | None = Field(
        default=None, description="Whether the message is the end of a recipe generation"
    )

class BaseMessageToolUsage(BaseModel):
    tool_name: str | None = Field(
        default=None, description="The tool name if the message was generated by a tool"
    )
    tool_input: dict | None = Field(
        default=None, description="The tool input if the message was generated by a tool"
    )
    tool_output: dict | None = Field(
        default=None, description="The tool output if the message was generated by a tool"
    )

class BaseMessageAIModel(BaseModel):
    model_name: str | None = Field(
        default=None, description="The AI model used to generate the message"
    )
    input_tokens: int | None = Field(
        default=None, description="The number of input tokens used to generate the message"
    )
    output_tokens: int | None = Field(
        default=None, description="The number of output tokens used to generate the message"
    )

class BaseMessageSafetyGuardResult(BaseModel):
    safety_guard_result: SafetyGuardResult | None = Field(
        default=None,
        description="Safety guard result including safety issues, blocked reason, and score",
    )

class BaseMessageIPAddress(BaseModel):
    ip_address: str | None = Field(
        default=None, description="The IP address of the user who sent the message"
    )

class Message(
    BaseMessage,
    BaseMessageParent,
    BaseMessageTextContent,
    BaseMessageRecipeGeneration,
    BaseMessageToolUsage,
    BaseMessageAIModel,
    BaseMessageSafetyGuardResult,
    BaseMessageIPAddress,
):
    """A message in a thread."""
    pass

class ApiMessage(
    BaseMessage,
    BaseMessageParent,
    BaseMessageTextContent,
    BaseMessageRecipeGeneration,
    BaseMessageToolUsage,
    BaseMessageAIModel,
):
    """A message in a thread for response to the client. This message does not include any sensitive fields like ip_address and safety_guard_result."""

    @classmethod
    def from_message(cls, message: Message) -> "ApiMessage":
        """Create a ApiMessage object from a Message object, excluding sensitive fields."""
        return cls(
            id=message.id,
            user_id=message.user_id,
            thread_id=message.thread_id,
            role=message.role,
            content_type=message.content_type,
            text_content=message.text_content,
            parent_id=message.parent_id,
            recipe_id=message.recipe_id,
            created_at=message.created_at,
            updated_at=message.updated_at,
            model_name=message.model_name,
            input_tokens=message.input_tokens,
            output_tokens=message.output_tokens,
            tool_name=message.tool_name,
            tool_input=message.tool_input,
            tool_output=message.tool_output,
            is_recipe_generation_started=message.is_recipe_generation_started,
            is_recipe_generation_completed=message.is_recipe_generation_completed,
        )

class PaginatedMessages(BaseModel):
    """Paginated list of messages for a thread."""

    messages: list[Message] = Field(
        description="The paginated list of messages for the current page"
    )
    total_count: int = Field(
        description="The total number of messages available in the thread across all pages"
    )
    has_more: bool = Field(
        description="Indicates whether there are additional pages of messages available beyond the current page"
    )
    next_timestamp: str | None = Field(
        description="The timestamp of the last message in the current page, used as the cursor for fetching the next page of messages, null if no more pages exist"
    )
    
class PaginatedApiMessages(BaseModel):
    """Paginated list of message responses for a thread."""
    
    messages: list[ApiMessage] = Field(
        description="The paginated list of messages for the current page"
    )
    total_count: int = Field(
        description="The total number of messages available in the thread across all pages"
    )
    has_more: bool = Field(
        description="Indicates whether there are additional pages of messages available beyond the current page"
    )
    next_timestamp: str | None = Field(
        description="The timestamp of the last message in the current page, used as the cursor for fetching the next page of messages, null if no more pages exist"
    )
    
    @classmethod
    def from_paginated_messages(cls, paginated_messages: PaginatedMessages) -> "PaginatedApiMessages":
        return cls(
            messages=[ApiMessage.from_message(message) for message in paginated_messages.messages],
            total_count=paginated_messages.total_count,
            has_more=paginated_messages.has_more,
            next_timestamp=paginated_messages.next_timestamp
        )
    

class GetThreadMessagesResponse(BaseModel):
    """Response for getting thread messages with associated recipes."""

    paginated_messages: PaginatedApiMessages = Field(
        description="The paginated messages for the thread"
    )
    recipes: list[UserRecipe] = Field(
        description="The recipes associated with the messages in the thread"
    )

class GetMessagesParams(BaseModel):
    """Parameters for getting messages with pagination, sorting, and timestamp filtering.

    Attributes:
        - user_id: The associated user's id
        - thread_id: The associated thread's id
        - limit: Number of messages to return (min 1, max 100) (default: 10)
        - from_timestamp: Timestamp to start filtering from (exclusive)
        - sort_by: Field to sort by (created_at or updated_at) (default: created_at)
        - sort_order: Sort order (asc or desc) (default: desc)
    """

    user_id: str = Field(description="The associated user's id")
    thread_id: str = Field(description="The associated thread's id")
    limit: int = Field(ge=1, le=100, default=10, description="Number of messages to return")
    from_timestamp: datetime | None = Field(
        default=None, description="Timestamp to start from filtering messages (exclusive)"
    )
    sort_by: Literal["created_at", "updated_at"] = Field(
        default="created_at", description="Field to sort by"
    )
    sort_order: Literal["asc", "desc"] = Field(default="desc", description="Sort order")

class GetDBMessagesParams(BaseModel):
    """Parameters for getting messages with pagination, sorting, and timestamp filtering.

    Attributes:
        - user_id: The associated user's id
        - thread_id: The associated thread's id
        - limit: Number of messages to return (min 1, max 101) (default: 10) (100+1 for paginated limit and has_more flag)
        - from_timestamp: Timestamp to start filtering from (exclusive)
        - sort_by: Field to sort by (created_at or updated_at) (default: created_at)
        - sort_order: Sort order (asc or desc) (default: desc)
    """

    user_id: str = Field(description="The associated user's id")
    thread_id: str = Field(description="The associated thread's id")
    limit: int = Field(
        ge=1,
        le=101,
        default=10,
        description="Number of messages to return (100+1 for paginated limit and has_more flag)",
    )
    from_timestamp: datetime | None = Field(
        default=None, description="Timestamp to start from filtering messages (exclusive)"
    )
    sort_by: Literal["created_at", "updated_at"] = Field(
        default="created_at", description="Field to sort by"
    )
    sort_order: Literal["asc", "desc"] = Field(default="desc", description="Sort order")

class CreateMessageParams(
    BaseMessageParent,
    BaseMessageTextContent,
    BaseMessageToolUsage,
    BaseMessageRecipeGeneration,
    BaseMessageAIModel,
    BaseMessageSafetyGuardResult,
    BaseMessageIPAddress,
):
    """Base parameters for message operations."""

    id: str = Field(description="The message's id")
    user_id: str = Field(description="The associated user's id")
    thread_id: str = Field(description="The associated thread's id")
    role: MessageRole = Field(description="Who created the message")
    content_type: MessageContentType = Field(description="The message's content type")
    created_at: datetime = Field(description="When the message was created")
    updated_at: datetime = Field(description="When the message was last updated")

class RoleAndContentTypeMixin(BaseModel):
    """Mixin for messages with role and content type."""

    default_role: ClassVar[MessageRole]
    default_content_type: ClassVar[MessageContentType]

    def __init__(self, **data):
        if "role" not in data:
            data.setdefault("role", self.default_role)
        if "content_type" not in data:
            data.setdefault("content_type", self.default_content_type)
        super().__init__(**data)

class TextContentMixin(BaseModel):
    """Mixin for messages with text content."""

    default_text_content: ClassVar[str] = ""

    def __init__(self, **data):
        if "text_content" not in data:
            data.setdefault("text_content", self.default_text_content)
        super().__init__(**data)

def validate_parent_id(v: str) -> str:
    v = v.strip() if v else ""
    if not v:
        raise ValueError("parent_id is required and cannot be empty")
    return v

class ParentIdMixin(BaseModel):
    """Mixin for messages with parent id."""

    parent_id: Annotated[
        str, Field(description="The parent message's id"), AfterValidator(validate_parent_id)
    ]

class CreateUserMessageParams(RoleAndContentTypeMixin, TextContentMixin, CreateMessageParams):
    """Parameters for creating a user message."""

    default_role: ClassVar[MessageRole] = MessageRole.user
    default_content_type: ClassVar[MessageContentType] = MessageContentType.text

class CreateAssistantTextMessageParams(
    RoleAndContentTypeMixin, TextContentMixin, ParentIdMixin, CreateMessageParams
):
    """Parameters for creating an assistant text message."""

    default_role: ClassVar[MessageRole] = MessageRole.assistant
    default_content_type: ClassVar[MessageContentType] = MessageContentType.text

class CreateAssistantRecipeMessageParams(
    RoleAndContentTypeMixin, ParentIdMixin, CreateMessageParams
):
    """Parameters for creating an assistant recipe message."""

    default_role: ClassVar[MessageRole] = MessageRole.assistant
    default_content_type: ClassVar[MessageContentType] = MessageContentType.recipe

class CreateAssistantToolMessageParams(RoleAndContentTypeMixin, ParentIdMixin, CreateMessageParams):
    """Parameters for creating an assistant tool message."""

    default_role: ClassVar[MessageRole] = MessageRole.assistant
    default_content_type: ClassVar[MessageContentType] = MessageContentType.tool


class UpdateStrategy(Enum):
    """Strategy for updating a message, either replace or append."""

    REPLACE = "replace"
    APPEND = "append"

class UpdateMessageTextContentParams(BaseModel):
    """Parameters for updating a message's text content.
    
    Attributes:
        - text_content: The message's text content
        - strategy: The strategy for updating the message's text content
    """

    text_content: str = Field(description="The message's text content")
    strategy: UpdateStrategy = Field(default=UpdateStrategy.REPLACE, description="The strategy for updating the message's text content")

class UpdateMessageInputTokensParams(BaseModel):
    """Parameters for updating a message's token usage.
    
    Attributes:
        - input_tokens: The number of input tokens used
        - strategy: The strategy for updating the message's input tokens
    """

    input_tokens: int = Field(description="The number of input tokens used")
    strategy: UpdateStrategy = Field(default=UpdateStrategy.REPLACE, description="The strategy for updating the message's input tokens")

class UpdateMessageOutputTokensParams(BaseModel):
    """Parameters for updating a message's token usage.
    
    Attributes:
        - output_tokens: The number of output tokens used
        - strategy: The strategy for updating the message's output tokens
    """

    output_tokens: int = Field(description="The number of output tokens used")
    strategy: UpdateStrategy = Field(default=UpdateStrategy.REPLACE, description="The strategy for updating the message's output tokens")

class UpdateMessageParams(
    BaseMessageParent,
    BaseMessageToolUsage,
    BaseMessageRecipeGeneration,
    BaseMessageSafetyGuardResult,
    BaseMessageIPAddress,
):
    """Parameters for updating a message."""

    id: str = Field(description="The message's id")
    updated_at: datetime = Field(description="When the message was last updated")
    model_name: str | None = Field(default=None, description="The AI model used to generate the message")
    
    text_content_update: UpdateMessageTextContentParams | None = Field(default=None, description="The message's text content")
    input_tokens_update: UpdateMessageInputTokensParams | None = Field(default=None, description="The message's input tokens")
    output_tokens_update: UpdateMessageOutputTokensParams | None = Field(default=None, description="The message's output tokens")

class CountMessagesParams(BaseModel):
    """Filters for counting messages."""
    
    thread_id: str | None = None
    user_id: str | None = None
    role: MessageRole | None = None

