# fly.staging.toml app configuration file for brekkie-ai-staging
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "brekkie-ai-staging"
primary_region = "iad"

[build.args]
  VITE_API_BASE_URL = "https://brekkie-ai-staging.fly.dev/api"
  VITE_WS_BASE_URL = "wss://brekkie-ai-staging.fly.dev/ws"
  VITE_AUTH0_DOMAIN = "dev-1oqfxpe3kn4ryzgd.us.auth0.com"
  VITE_AUTH0_CLIENT_ID = "vafgkJisEfwLdFqUtG2xW3Lbi63XaxYr"
  MODE = "staging"

[env]
  PORT = "8080"
  ENVIRONMENT = "staging"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20 