# fly.toml app configuration file generated for brekkie-ai on 2024-01-01T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "brekkie-ai"
primary_region = "iad"

[build.args]
  VITE_API_BASE_URL = "https://brekkie-ai.fly.dev/api"
  VITE_WS_BASE_URL = "wss://brekkie-ai.fly.dev/ws"
  VITE_APP_BASE_URL = "https://brekkie-ai.fly.dev"
  VITE_SUPABASE_URL = "https://towqqrlctvsstlntfxtf.supabase.co"
  MODE = "production"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  min_machines_running = 1 # Keep at least 1 vm warm ready for chat
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "60s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
    