"""Add ip address and safety guard to Message

Revision ID: 7f91cd49ab52
Revises: 781a8252ecfe
Create Date: 2025-07-11 19:48:30.332311

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f91cd49ab52'
down_revision: Union[str, None] = '781a8252ecfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('safety_guard_result', sa.JSON(), nullable=True))
    # Note: safety_metadata column was never created, so we don't need to drop it
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'safety_guard_result')
    op.drop_column('messages', 'ip_address')
    # Note: safety_metadata column was never created, so we don't need to add it back
    # ### end Alembic commands ###
